//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE104_N10_QuanLySieuThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string SOHD { get; set; }
        public string NGHD { get; set; }
        public string MAKH { get; set; }
        public string MANV { get; set; }
        public Nullable<decimal> TRIGIA { get; set; }
    
        public virtual CTHD CTHD { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
