//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE104_N10_QuanLySieuThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.HOADON = new HashSet<HOADON>();
        }
    
        public string MAKH { get; set; }
        public string HOTEN { get; set; }
        public string SODT { get; set; }
        public Nullable<decimal> DOANHSO { get; set; }
        public string ACC { get; set; }
        public byte[] PICBI { get; set; }
        public string MAIL { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> NGSINH { get; set; }
        public Nullable<System.DateTime> NGDK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADON { get; set; }
    }
}
