//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE104_N10_QuanLySieuThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPHANG
    {
        public string MANH { get; set; }
        public string MANV { get; set; }
        public string MASP { get; set; }
        public Nullable<int> SLNHAPHANG { get; set; }
        public Nullable<System.DateTime> NGNH { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
